# [general]
# aligner: bwa
illumina: True
GENOME: /home/dlf/Code/SnakeMake/artic_ncov2019/ref/nCoV-2019/V3/nCoV-2019.reference.fasta
FASTQ_DIR: /media/dlf/Learning/Code/NGS/SARSCoV2/SRA
SAMPLE_SHEET: /home/dlf/Code/SnakeMake/artic_ncov2019/test_data/samplesheet.tsv
VCF_QUAL_FILTER: 32
OUT_DIR: /home/dlf/Code/SnakeMake/artic_ncov2019/results
PRIMER_DIR: /home/dlf/Code/SnakeMake/artic_ncov2019/ref/nCoV-2019/V3

# corgat configuration
corgatPath: /home/dlf/Code/SnakeMake/artic_ncov2019/CorGAT
corgatFna: /home/dlf/Code/SnakeMake/artic_ncov2019/CorGAT/GCF_009858895.2_ASM985889v3_genomic.fna
corgatConf: /home/dlf/Code/SnakeMake/artic_ncov2019/CorGAT/corgat.conf
# typing configuration
gff: '/home/dlf/Code/SnakeMake/artic_ncov2019/typing/MN908947.3.gff'
typing_yaml: '/home/dlf/Code/SnakeMake/artic_ncov2019/typing/SARS-CoV-2.types.yaml'
# Output cram instead of bam files
outCram: False

# Clean BAM header to anonymise fastq names
cleanBamHeader: False

# Allow reads that don't have primer sequence? Ligation prep: False, nextera: True
allowNoprimer: True

# Length of illumina reads to keep after primer trimming
illuminaKeepLen: 30

# Sliding window quality threshold for keeping reads after primer trimming (illumina)
illuminaQualThreshold: 20

# Mpileup depth for ivar (although undocumented in mpileup, setting to zero removes limit)
mpileupDepth: 0

# iVar frequency threshold for consensus variant (ivar consensus: -t)
ivarFreqThreshold: 0.75

# Minimum coverage depth to call variant (ivar consensus: -m; ivar variants -m)
ivarMinDepth: 10

# iVar frequency threshold to call variant (ivar variants: -t )
ivarMinFreqThreshold: 0.25

# iVar minimum mapQ to call variant (ivar variants: -q)
ivarMinVariantQuality: 20

# Typing frequency threshold to call aa consequences of variant. Set to ivarFreqThreshold for consistency with consensus
csqAfThreshold: 0.75

# Minimum coverage depth to call aa consequences of variant. Set to ivarMinDepth for consistency with consensus
csqDpThreshold: 10